language: android
  
sudo: required
dist: trusty

os:
  - linux

env:
  matrix:
    - env: LAZ_VER=1.8.0RC5 
    - env: LAZ_VER=1.8RC5  LAZ_ENV=wine LAZ_OPT="--os=win32 --cpu=i386"

install:
  - git clone https://github.com/benibela/travis-lazarus travis-lazarus
  - travis-lazarus/.travis.install.py
  - if [[ "$LAZ_ENV" = wine ]]; then find $WINEPREFIX -iname '*fpc.cfg' | head -1 | xargs -i{} ln {} ~/.fpc.cfg; ls -l ~; fi
  - if [[ ! -e ~/.fpc.cfg ]]; then echo '#INCLUDE /etc/fpc.cfg' > ~/.fpc.cfg; fi 
  #get dependencies from sourceforge
  - mkdir github; mv * github 2>/dev/null;
  - hg clone http://hg.code.sf.net/p/videlibri/code videlibri
  - git clone https://github.com/benibela/flre.git import/flre; 
  - echo "-Fuimport/flre/src/ -Fu " >> ~/.fpc.cfg;

script:
  - lazbuild $LAZ_OPT --add-package components/pascal/internettools.lpk
  - lazbuild $LAZ_OPT --add-package components/pascal/internettools_autoupdate.lpk
  - lazbuild $LAZ_OPT programs/internet/xidel/xidel.lpi
  - lazbuild $LAZ_OPT bookWatch.lpi

notifications:
  email:
    on_success: false
    on_failure: change