language: android
  
sudo: required
dist: trusty

os:
  - linux

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0

matrix:
  include:
    - env: LAZ_VER=1.8.0RC5 android=false
    - env: LAZ_VER=1.8RC5  LAZ_ENV=wine LAZ_OPT="--os=win32 --cpu=i386" android=false
    - env: LAZ_VER=1.8.0RC5  android=true FPC_VER=3.0.4 FPC_DIRECTORY=/usr/lib/fpc/$FPC_VER/

android:
  components:
    - tools
    - platform-tools
    - tools

install:
  - git clone https://github.com/benibela/travis-lazarus travis-lazarus
  - travis-lazarus/.travis.install.py
  - if [[ "$LAZ_ENV" = wine ]]; then find $WINEPREFIX -iname '*fpc.cfg' | head -1 | xargs -i{} ln {} ~/.fpc.cfg; ls -l ~; fi
  - if [[ ! -e ~/.fpc.cfg ]]; then echo '#INCLUDE /etc/fpc.cfg' > ~/.fpc.cfg; fi 
  - cd ..
  #get dependencies from sourceforge
  - hg clone http://hg.code.sf.net/p/videlibri/code sf
  - rm -rf sf/programs/internet/VideLibri; mv videlibri sf/programs/internet/VideLibri; cd sf
  - mkdir import; git clone https://github.com/benibela/flre.git import/flre; 
  - echo -Fu$PWD/import/flre/src/ >> ~/.fpc.cfg;
  - echo -Fi$PWD/components/pascal/ >> ~/.fpc.cfg;
  - echo -Fi$PWD/components/pascal/data >> ~/.fpc.cfg;
  - echo -Fu$PWD/components/pascal/data >> ~/.fpc.cfg;
  - ln -s $PWD/import/flre components/pascal/import/flre
  - cat ~/.fpc.cfg
  - echo Fu$PWD/components/pascal/data
  - if [[ $android = true ]]; then 
      yes | sdkmanager ndk-bundle "build-tools;25.0.3"  "platforms;android-25";
      sudo apt-get install -y gcc-arm-linux-androideabi libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386;
      oldpath=$PWD;
      cd /usr/share/fpcsrc/3* ;
      sudo make crossinstall OS_TARGET=android CPU_TARGET=arm BINUTILSPREFIX=arm-linux-androideabi- INSTALL_PREFIX=/usr;
      sudo make crossinstall OS_TARGET=android CPU_TARGET=i386 BINUTILSPREFIX=i686-linux-android- INSTALL_PREFIX=/usr;
      cd $oldpath;
      gccv=$(gcc-arm-linux-androideabi -dumpversion);
      echo '#IFDEF CPUARM' >> ~/.fpc.cfg;
      echo '-XParm-linux-androideabi-' >> ~/.fpc.cfg;
      for l in  /usr/local/android-sdk-*/ndk-bundle/platforms/android-24/arch-arm/usr/lib /usr/lib/gcc/arm-linux-androideabi/* /usr/arm-linux-androideabi/lib; do echo -Fl$l >> ~/.fpc.cfg; done;
      echo '#ENDIF' >> ~/.fpc.cfg;
      echo '#IFDEF CPU386' >> ~/.fpc.cfg;
      echo '-XPi686-linux-android-'  >> ~/.fpc.cfg;
      for l in /usr/local/android-sdk/ndk-bundle/platforms/android-24/arch-x86/usr/lib/ /usr/lib/gcc/i686-linux-gnu/* /usr/lib/gcc/i586-mingw32msvc/*; do echo -Fl$l >> ~/.fpc.cfg; done;
      echo '#ENDIF' >> ~/.fpc.cfg;
      cat ~/.fpc.cfg;
      find /usr/local/android-sdk/ndk-bundle/ -name "i686-linux-android-ld";
    fi
  - if [[ $LAZ_ENV = wine ]]; then  
      sudo apt-get install -y dos2unix;
      tee programs/internet/xidel/xidel <<<$'#!/bin/bash\nwine ../../../xidel/xidel.exe "$@" | dos2unix | perl -pne \' s!(file://Z:[^"]+)! {my $temp = $1; $temp =~ s%(Z:)?\\\\{1,2}%/%g; $temp}!ge\'';
      chmod +x programs/internet/xidel/xidel;
    fi

#    svn checkout -r 37480 https://svn.freepascal.org/svn/fpc/trunk	fpc-trunk
#    cd fpc-trunk
      
      
script:
  - env
  - lazbuild $LAZ_OPT --add-package components/pascal/data/searchbarpackage.lpk
  - lazbuild $LAZ_OPT --add-package components/pascal/data/treelistviewpackage.lpk
  - lazbuild $LAZ_OPT --add-package components/pascal/internettools.lpk
  - touch programs/internet/xidel/xidelbuilddata.inc; lazbuild $LAZ_OPT programs/internet/xidel/xidel.lpi
  - lazbuild $LAZ_OPT programs/internet/VideLibri/_meta/assetversiontests.lpi
  - if [[ $android = false ]]; then lazbuild $LAZ_OPT programs/internet/VideLibri/bookWatch.lpi; fi
  - if [[ $android = true ]]; then cd programs/internet/VideLibri/android; ./manage.sh build && cd ../../../..; fi
  - export PATH=$PATH:$PWD/programs/internet/xidel/
  - $LAZ_ENV programs/internet/VideLibri/_meta/assetversiontests
  - cd programs/internet/VideLibri/_meta/tests;  ./unittests.sh

notifications:
  email:
    on_failure: change