language: android
  
sudo: required
dist: trusty

os:
  - linux

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0

matrix:
  include:
    - env: LAZ_VER=1.8.0RC5 android=false
    - env: LAZ_VER=1.8RC5  LAZ_ENV=wine LAZ_OPT="--os=win32 --cpu=i386" android=false
    - env: LAZ_VER=1.8.0RC5  android=true FPC_VER=3.0.4 FPC_DIRECTORY=/usr/lib/fpc/$FPC_VER/


components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.3
  - android-25
  - ndk-bundle

install:
  - git clone https://github.com/benibela/travis-lazarus travis-lazarus
  - travis-lazarus/.travis.install.py
  - if [[ "$LAZ_ENV" = wine ]]; then find $WINEPREFIX -iname '*fpc.cfg' | head -1 | xargs -i{} ln {} ~/.fpc.cfg; ls -l ~; fi
  - if [[ ! -e ~/.fpc.cfg ]]; then echo '#INCLUDE /etc/fpc.cfg' > ~/.fpc.cfg; fi 
  - cd ..
  #get dependencies from sourceforge
  - hg clone http://hg.code.sf.net/p/videlibri/code sf
  - rm -rf sf/programs/internet/VideLibri; mv videlibri sf/programs/internet/VideLibri; cd sf
  - mkdir import; git clone https://github.com/benibela/flre.git import/flre; 
  - echo -Fu$PWD/import/flre/src/ >> ~/.fpc.cfg;
  - echo -Fi$PWD/components/pascal/ >> ~/.fpc.cfg;
  - echo -Fi$PWD/components/pascal/data >> ~/.fpc.cfg;
  - echo -Fu$PWD/components/pascal/data >> ~/.fpc.cfg;
  - ln -s $PWD/import/flre components/pascal/import/flre
  - cat ~/.fpc.cfg
  - echo Fu$PWD/components/pascal/data
  - if [[ $android = true ]]; then 
      sudo apt-get install -y gcc-arm-linux-androideabi libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386;
      sudo tee /usr/bin/i386-linux-as <<<$'#!/bin/bash\nas --32 $@';
      sudo tee /usr/bin/i386-linux-ld <<<$'#!/bin/bash\nld -A elf32-i386 $@';
      sudo chmod +x /usr/bin/i386-linux-*;
      oldpath=$PWD;
      cd /usr/share/fpcsrc/3* ;
      sudo make crossinstall OS_TARGET=android CPU_TARGET=arm BINUTILSPREFIX=arm-linux-androideabi- INSTALL_PREFIX=/usr;
      sudo make crossinstall OS_TARGET=android CPU_TARGET=i386 BINUTILSPREFIX=i386-linux- INSTALL_PREFIX=/usr;
      cd $oldpath;
      gccv=$(gcc-arm-linux-androideabi -dumpversion);
      echo '#IFDEF CPUARM' >> ~/.fpc.cfg;
      echo '-Xd' >> ~/.fpc.cfg;
      echo '-Xt' >> ~/.fpc.cfg;
      echo '-XParm-linux-androideabi-' >> ~/.fpc.cfg;
      ls -l /usr /usr/lib /usr/lib/gcc /usr/lib/gcc-cross /usr/lib/gcc/arm-linux-androideabi/* /usr/lib/gcc/arm-linux-androideabi/*;
      echo -Fl/usr/arm-linux-androideabi/lib >> ~/.fpc.cfg;
      echo -Fl/usr/lib/gcc/arm-linux-androideabi/* >> ~/.fpc.cfg;
      echo '#ENDIF' >> ~/.fpc.cfg;
      echo '#IFDEF CPU386' >> ~/.fpc.cfg;
      echo -Fl/usr/lib/gcc/i686-linux-gnu/* >> ~/.fpc.cfg;
      echo -Fl/usr/lib/gcc/i586-mingw32msvc/* >> ~/.fpc.cfg;
      echo '#ENDIF' >> ~/.fpc.cfg;
      cat ~/.fpc.cfg;
    fi
  - if [[ $LAZ_ENV = wine ]]; then  
      sudo apt-get install -y dos2unix;
      tee programs/internet/xidel/xidel <<<$'#!/bin/bash\nwine ../../../xidel/xidel.exe "$@" | dos2unix | perl -pne \' s!(file://Z:[^"]+)! {my $temp = $1; $temp =~ s%(Z:)?\\\\{1,2}%/%g; $temp}!ge\'';
    fi

#    svn checkout -r 37480 https://svn.freepascal.org/svn/fpc/trunk	fpc-trunk
#    cd fpc-trunk
      
      
script:
  - find $HOME /usr/lib -name libdl.so
  - lazbuild $LAZ_OPT --add-package components/pascal/data/searchbarpackage.lpk
  - lazbuild $LAZ_OPT --add-package components/pascal/data/treelistviewpackage.lpk
  - lazbuild $LAZ_OPT --add-package components/pascal/internettools.lpk
  - touch programs/internet/xidel/xidelbuilddata.inc; lazbuild $LAZ_OPT programs/internet/xidel/xidel.lpi
  - lazbuild $LAZ_OPT programs/internet/VideLibri/_meta/assetversiontests.lpi
  - if [[ $android = false ]]; then lazbuild $LAZ_OPT programs/internet/VideLibri/bookWatch.lpi; fi
  - if [[ $android = true ]]; then cd programs/internet/VideLibri/android; ./manage.sh build && cd ../../../..; fi
  - export PATH=$PATH:$PWD/programs/internet/xidel/
  - $LAZ_ENV programs/internet/VideLibri/_meta/assetversiontests
  - cd programs/internet/VideLibri/_meta/tests;  ./unittests.sh

notifications:
  email:
    on_failure: change