language: android
  
sudo: required
dist: trusty

os:
  - linux

env:
  - LAZ_VER=1.8.0RC5 
  - LAZ_VER=1.8RC5 
  - android=false
  - android=true

matrix:
  include:
    - env: LAZ_VER=1.8.0RC5 android=false
    - env: LAZ_VER=1.8RC5  LAZ_ENV=wine LAZ_OPT="--os=win32 --cpu=i386" android=false
    - env: LAZ_VER=1.8.0RC5  android=true

install:
  - git clone https://github.com/benibela/travis-lazarus travis-lazarus
  - travis-lazarus/.travis.install.py
  - if [[ "$LAZ_ENV" = wine ]]; then find $WINEPREFIX -iname '*fpc.cfg' | head -1 | xargs -i{} ln {} ~/.fpc.cfg; ls -l ~; fi
  - if [[ ! -e ~/.fpc.cfg ]]; then echo '#INCLUDE /etc/fpc.cfg' > ~/.fpc.cfg; fi 
  #get dependencies from sourceforge
  - hg clone http://hg.code.sf.net/p/videlibri/code sf
  - git clone https://github.com/benibela/flre.git import/flre; 
  - echo "-Fuimport/flre/src/ -Fu " >> ~/.fpc.cfg;

script:
  - lazbuild $LAZ_OPT --add-package sf/components/pascal/internettools.lpk
  - lazbuild $LAZ_OPT --add-package sf/components/pascal/internettools_autoupdate.lpk
  - lazbuild $LAZ_OPT sf/programs/internet/xidel/xidel.lpi
  - if [[ $android = false ]]; then lazbuild $LAZ_OPT bookWatch.lpi; fi
  - if [[ $android = true ]]; then cd android; ./manage.sh build; fi

notifications:
  email:
    on_success: false
    on_failure: change